name: Deploy to GitHub Pages

on:
  # Se ejecuta automáticamente al hacer push a "main"
  push:
    branches:
      - main
  # Permite ejecutar el Action manualmente desde la web
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔐 Inyectar Variables de Firebase
        # Busca los Strings temporales en FirebaseService.js y los 
        # sustituye por los valores reales alojados en GitHub Secrets.
        run: |
          sed -i "s|FIREBASE_API_KEY|${{ secrets.FIREBASE_API_KEY }}|g" src/js/FirebaseService.js
          sed -i "s|FIREBASE_AUTHDOMAIN|${{ secrets.FIREBASE_AUTHDOMAIN }}|g" src/js/FirebaseService.js
          sed -i "s|FIREBASE_PROJECTID|${{ secrets.FIREBASE_PROJECTID }}|g" src/js/FirebaseService.js
          sed -i "s|FIREBASE_DATABASEURL|${{ secrets.FIREBASE_DATABASEURL }}|g" src/js/FirebaseService.js
          sed -i "s|FIREBASE_STORAGEBUCKET|${{ secrets.FIREBASE_STORAGEBUCKET }}|g" src/js/FirebaseService.js
          sed -i "s|FIREBASE_MESSAGINGSENDERID|${{ secrets.FIREBASE_MESSAGINGSENDERID }}|g" src/js/FirebaseService.js
          sed -i "s|FIREBASE_APPID|${{ secrets.FIREBASE_APPID }}|g" src/js/FirebaseService.js
          sed -i "s|FIREBASE_MEASUREMENTID|${{ secrets.FIREBASE_MEASUREMENTID }}|g" src/js/FirebaseService.js

      - name: ⚙️ Setup Pages
        uses: actions/configure-pages@v4

      - name: 📦 Build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Si todos los archivos están en la carpeta principal se sube '.'
          path: '.'

      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
